name: Build and Test Library app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install

    - name: Manually change the config file
      run: echo "export const settings = {host:\"http://localhost:3030\"};" > src/config.js
      
    - name: Install playwright browsers
      run: npx playwright install

    - name: Start the Backend
      run: npm run start-be &

    - name: Start the FrontEnd
      run: npm run start-fe &
    
    - name: Run tests
      run: npm run test


  deploy-be:
    needs: build_and_test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.7
        with:
          service_id: ${{ secrets.BE_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true

  deploy-fe:
    needs: deploy-be
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.7
        with:
          service_id: ${{ secrets.FE_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true

        


